name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy ke EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.239.34.130 << 'EOF'
          cd /var/www/Sipesat-Frontend
          sudo git pull origin main
          sudo npm install
          sudo npm run build
          sudo systemctl reload nginx
          EOF